name: CI Pipeline)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # BACKEND
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install backend dependencies
        run: |
          pip install flake8 isort black pytest

      - name: Install app dependencies
        run: pip install -r Task_2/backend/requirements.txt

      - name: Run backend linters
        working-directory: Task_2
        run: |
          flake8 backend/
          isort --check-only --diff backend/
          black --check --diff backend/

      - name: Run backend tests
        working-directory: Task_2/backend
        run: |
          PYTHONPATH=$(pwd) pytest -v

      # FRONTEND
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install frontend dependencies
        run: npm ci
        working-directory: Task_2/frontend

      - name: Run frontend linter
        run: npx eslint .
        working-directory: Task_2/frontend

  build-and-scan:
    runs-on: ubuntu-latest
    needs: lint-and-test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build backend image
        run: docker build -f Task_2/backend/Dockerfile -t backend Task_2/backend

      - name: Build frontend image
        run: docker build -f Task_2/frontend/Dockerfile -t frontend Task_2/frontend

      - name: Install Trivy
        env:
          TRIVY_VERSION: "0.69.0"
        run: |
          wget https://github.com/aquasecurity/trivy/releases/download/v${TRIVY_VERSION}/trivy_${TRIVY_VERSION}_Linux-64bit.tar.gz
          tar zxvf trivy_${TRIVY_VERSION}_Linux-64bit.tar.gz
          sudo mv trivy /usr/local/bin/

      - name: Scan backend image
        run: |
          trivy image \
          --severity HIGH,CRITICAL \
          --exit-code 1 \
          --ignorefile .trivyignore \
          backend

      - name: Scan frontend image
        run: trivy image --severity HIGH,CRITICAL --exit-code 1 frontend